language: c

sudo: false

install:
  - ./script/build.sh -DCMAKE_INSTALL_PREFIX=$HOME/local
  - ./script/install.sh

script:
  - bekobrew --version
  - bekobrew install
  - run_test

env:
  - PATH=$PATH:$HOME/local/bin
