language: c

compiler:
  - clang
  - gcc

sudo: false

addons:
  apt:
    packages:
      - valgrind

install:
  - ./script/build.sh -DCMAKE_INSTALL_PREFIX=$HOME/local
  - ./script/install.sh

script:
  - bekobrew --version
  - bekobrew install
  - valgrind --leak-check=full --show-reachable=yes --error-exitcode=1 ./build/run_test

env:
  - PATH=$PATH:$HOME/local/bin

cache:
  directories:
    - build/
